export const Properties = [
  {
    id: "1",
    title: "Equestrian Villa",
    featured_image: "/property-1.jpg",
    image_gallery: [""],
    type: "villa",
    city: "miami",
    for: "for sale",
    price: "1599000",
    area: "15000",
    posted_by: "samuel palmer",
    path: "/",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. ",
    bedrooms: "4",
    bathrooms: "2",
    garage: "1",
    year_built: "2016",
  },
  {
    id: "2",
    title: "Light and modern apartment",
    featured_image: "/property-2.jpg",
    image_gallery: [""],
    type: "apartment",
    city: "miami",
    for: "for rent",
    price: "4500",
    area: "15000",
    posted_by: "samuel palmer",
    path: "/",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. ",
    bedrooms: "4",
    bathrooms: "2",
    garage: "1",
    year_built: "2016",
  },
  {
    id: "3",
    title: "New home for sale",
    featured_image: "/property-3.jpg",
    image_gallery: [""],
    type: "single family home",
    city: "miami",
    for: "for sale",
    price: "453000",
    area: "2560",
    posted_by: "samuel palmer",
    path: "/",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. ",
    bedrooms: "4",
    bathrooms: "2",
    garage: "1",
    year_built: "2019",
  },

  {
    id: "4",
    title: "Guaranteed modern home",

    featured_image: "/property-4.jpg",
    image_gallery: [""],
    type: "single family home",
    city: "miami",
    for: "for sale",
    price: "590000",
    area: "3500",
    posted_by: "samuel palmer",
    path: "/",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. ",
    bedrooms: "4",
    bathrooms: "2",
    garage: "1",
    year_built: "2016",
  },
  {
    id: "5",
    title: "Renovated studio",
    featured_image: "/property-5.jpg",
    image_gallery: [""],
    type: "studio",
    city: "new york",
    for: "for sale",
    price: "540000",
    area: "3700",
    posted_by: "samuel palmer",
    path: "/",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. ",
    bedrooms: "4",
    bathrooms: "2",
    garage: "",
    year_built: "2018",
  },
  {
    id: "6",
    title: "Design apartment",
    featured_image: "/property-6.jpg",
    image_gallery: [""],
    type: "apartment",
    city: "miami",
    for: "for sale",
    price: "876000",
    area: "2590",
    posted_by: "samuel palmer",
    path: "/",
    desc: "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. ",
    bedrooms: "4",
    bathrooms: "2",
    garage: "1",
    year_built: "2020",
  },
];
